./ex1 >> output.txt
./ex1 >> output.txt
./ex1 >> output.txt
./ex1 >> output.txt
./ex1 >> output.txt
./ex1 >> output.txt
./ex1 >> output.txt
./ex1 >> output.txt
./ex1 >> output.txt
./ex1 >> output.txt
